const arr = [
  "jpg",
  "png",
  "psd",
  "ai",
  "html",
  "docx",
  "jar",
  "m4a",
  "tmp",
  "pdf",
  "mp4",
  "mp3",
  "gif",
  "jpeg",
  "js",
  "css",
  "txt",
  "ts",
  "py",
  "jsx",
];

const name = [
  "scoala",
  "liceu",
  "proiecte",
  "programare",
  "poze",
  "documente",
  "files",
  "jocuri",
  "engleza",
  "image",
  "zoom",
  "teme",
  "portofoliu",
  "statistici",
  "templates",
  "muzica",
  "screenshort",
];

const marime = [];

const date = [];

for (let i = 0; i < 100; i++){
  marime.push(i);
}

for (let i = 0; i < 200; i++){
  date.push(i);
}


const data = [
  {
    id: 0,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 1,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 2,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 3,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 4,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 5,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 6,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 7,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 8,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 9,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 10,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 11,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 12,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 13,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 14,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 15,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 16,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 17,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 18,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 19,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 20,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 21,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 22,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 23,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 24,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 25,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 26,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 27,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 28,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 29,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 30,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 31,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 32,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 33,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 34,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 35,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 36,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 37,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 38,
    name: "programare",
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: "js",
    link: "/Dif",
  },
  {
    id: 39,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 40,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 41,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 42,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 43,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 44,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 45,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 46,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 47,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 48,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 49,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 50,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 51,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 52,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 53,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 54,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 55,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 56,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 57,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 58,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 59,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
  {
    id: 60,
    name: name[Math.floor(Math.random() * name.length)],
    marime: marime[Math.floor(Math.random() * 100 + 1)],
    data: date[Math.floor(Math.random() * 200 + 1)],
    extensie: arr[Math.floor(Math.random() * arr.length)],
    link: "javascript:void(0)",
  },
];

const array = [data, name, arr, marime, date]

export default array;
